[package]
name = "bytestack-proto"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gen-format-v1"
path = "rust-gen-src/gen-v1.rs"


[dependencies]
prost = "0.11.9"
tonic = "0.9.2"
tonic-build = "0.9.2"
